import type { Metadata } from "next";
import localFont from "next/font/local";
import ChatSidebar from "@/components/ChatSidebar";

import "./globals.css";
import { Button } from "@/components/ui/button";
import { VolumeX } from "lucide-react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});


const alpina = localFont({
  src: './fonts/alpina.otf',
  variable: '--alpina',
  weight: "100 900"
});

const alpinaDense = localFont({
  src: './fonts/alpina-dense.otf',
  variable: '--alpina-dense',
  weight: "100 900"
});

export const metadata: Metadata = {
  title: "Pi, your personal Ai",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="icon" href="/favicon.svg" sizes="any" />
      <body
        className={`${alpina.variable} ${alpinaDense.variable} ${geistSans.variable} antialiased overflow-y-auto`}
      >
        <div className='flex  alpina h-full w-full overflow-y-auto'>
          <ChatSidebar />

          {children}
            <Button
            variant="ghost"
            size="icon"
            className="absolute text-primary-foreground p-0 z-50 top-4 right-4 rounded-full"
            >
              <VolumeX className="shrink-0 w-10 h-10" fill="#877c6c" strokeWidth={1} />
            </Button>
        </div>

      </body>
    </html>
  );
}
