import type { Metadata } from "next";
import localFont from "next/font/local";
import ChatSidebar from "@/components/ChatSidebar";



import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const alpina = localFont({
  src: './fonts/alpina.otf',
  variable: '--alpina',
  weight: "100 900"
});

const alpinaDense = localFont({
  src: './fonts/alpina-dense.otf',
  variable: '--alpina-dense',
  weight: "100 900"
});

export const metadata: Metadata = {
  title: "Pi, your personal Ai",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="icon" href="/favicon.svg" sizes="any" />
      <body
        className={`${alpina.variable} ${alpinaDense.variable} ${geistMono.variable} ${geistSans.variable} antialiased overflow-y-auto`}
      >
        <div className='flex  alpina h-full w-full overflow-y-auto'>
          <ChatSidebar />

          {children}
        </div>

      </body>
    </html>
  );
}
